// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiMedicines.Models
{
    public partial class Customers
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? Dni { get; set; }
        public decimal? Balance { get; set; }
    }
}