// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using WebApiMedicines.Models.Configurations;
#nullable disable

namespace WebApiMedicines.Models
{
    public partial class MedicinesAPIContext : DbContext
    {
        public MedicinesAPIContext()
        {
        }

        public MedicinesAPIContext(DbContextOptions<MedicinesAPIContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Medicines> Medicines { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.MedicinesConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
