// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Model.Models.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace Model.Models
{
    public partial class MedicinesAPIContext : DbContext
    {
        public MedicinesAPIContext()
        {
        }

        public MedicinesAPIContext(DbContextOptions<MedicinesAPIContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sells> Sells { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.MedicinesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RoleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SellsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsersConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
