// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiMedicines.Models
{
    public partial class Sells
    {
        public int IdMedicine { get; set; }
        public int IdUser { get; set; }
        public decimal? Amount { get; set; }
    }
}