// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Sells
    {
        public int Id { get; set; }
        public int IdMedicine { get; set; }
        public int IdUser { get; set; }
        //agregar SellDate a lo largo del programa
        public DateTime SellDate { get; set; }
        public decimal Amount { get; set; }

        public virtual Medicines IdMedicineNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
    }
}