// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Users
    {
        public Users()
        {
            Sells = new HashSet<Sells>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int IdRole { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public virtual Role IdRoleNavigation { get; set; }
        public virtual ICollection<Sells> Sells { get; set; }
    }
}