// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WebApiMedicines.Models;

namespace WebApiMedicines.Models.Configurations
{
    public partial class SellsConfiguration : IEntityTypeConfiguration<Sells>
    {
        public void Configure(EntityTypeBuilder<Sells> entity)
        {
            entity.HasKey(e => new { e.IdMedicine, e.IdUser });

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 0)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Sells> entity);
    }
}
